// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9EAJIR_HaRkobD7gHYsPXEISHbyT-KHo',
    appId: '1:1093300791595:web:b1f0b32b4e2c45e330bd6e',
    messagingSenderId: '1093300791595',
    projectId: 'avian-bird-450222-k1',
    authDomain: 'avian-bird-450222-k1.firebaseapp.com',
    storageBucket: 'avian-bird-450222-k1.firebasestorage.app',
    measurementId: 'G-6Q3JH9YYXN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0jO9AZDSdzl4Q0ifVWwwIYM9bSjgcMZ4',
    appId: '1:1093300791595:android:a2f925712210879130bd6e',
    messagingSenderId: '1093300791595',
    projectId: 'avian-bird-450222-k1',
    storageBucket: 'avian-bird-450222-k1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz3ByDewfKbTpLmDFI4yBEw3njIFPXMbU',
    appId: '1:1093300791595:ios:c09819ff6ed0d23330bd6e',
    messagingSenderId: '1093300791595',
    projectId: 'avian-bird-450222-k1',
    storageBucket: 'avian-bird-450222-k1.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );
}
